In [ ]:
import pandas as pd, numpy as np 

In [5]:
data = pd.read_csv("diamond.csv")
print(data)

     Unnamed: 0  carat colour clarity certification  price
0             1   0.30      D     VS2           GIA   1302
1             2   0.30      E     VS1           GIA   1510
2             3   0.30      G    VVS1           GIA   1510
3             4   0.30      G     VS1           GIA   1260
4             5   0.31      D     VS1           GIA   1641
..          ...    ...    ...     ...           ...    ...
303         304   1.01      I     VS1           HRD   8175
304         305   1.02      F    VVS2           HRD  10796
305         306   1.06      H    VVS2           HRD   9890
306         307   1.02      H     VS2           HRD   8959
307         308   1.09      I    VVS2           HRD   9107

[308 rows x 6 columns]


In [6]:
x_list = ['carat','price']
x = data[x_list]
x


carat  price
0     0.30   1302
1     0.30   1510
2     0.30   1510
3     0.30   1260
4     0.31   1641
..     ...    ...
303   1.01   8175
304   1.02  10796
305   1.06   9890
306   1.02   8959
307   1.09   9107

[308 rows x 2 columns]

In [7]:
y = (data.certification == "GIA")* 1
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
303    0
304    0
305    0
306    0
307    0
Name: certification, Length: 308, dtype: int32


In [8]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 50)

In [10]:
gini_model = DecisionTreeClassifier(criterion = "gini", max_depth = 7, max_leaf_nodes = 10, min_samples_leaf = 10, random_state=12)

In [11]:
gini_model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=7, max_leaf_nodes=10, min_samples_leaf=10,
                       random_state=12)

In [12]:
predictions = gini_model.predict(x_test)
predictions

array([0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0])

In [13]:
probability = gini_model.predict_proba(x_test)
probability 

array([[0.5106383 , 0.4893617 ],
       [0.34210526, 0.65789474],
       [0.83333333, 0.16666667],
       [0.18181818, 0.81818182],
       [0.83333333, 0.16666667],
       [0.07142857, 0.92857143],
       [0.18181818, 0.81818182],
       [0.83333333, 0.16666667],
       [1.        , 0.        ],
       [0.34210526, 0.65789474],
       [0.34210526, 0.65789474],
       [0.07142857, 0.92857143],
       [0.76923077, 0.23076923],
       [0.34210526, 0.65789474],
       [0.07142857, 0.92857143],
       [0.5       , 0.5       ],
       [0.83333333, 0.16666667],
       [0.18181818, 0.81818182],
       [0.2       , 0.8       ],
       [1.        , 0.        ],
       [0.34210526, 0.65789474],
       [0.18181818, 0.81818182],
       [0.83333333, 0.16666667],
       [0.83333333, 0.16666667],
       [1.        , 0.        ],
       [0.53846154, 0.46153846],
       [0.53846154, 0.46153846],
       [0.53846154, 0.46153846],
       [0.5106383 , 0.4893617 ],
       [0.53846154, 0.46153846],
       [0.

In [14]:
report = classification_report(y_test, predictions)
print(report)

              precision    recall  f1-score   support

           0       0.54      0.77      0.64        44
           1       0.67      0.41      0.51        49

    accuracy                           0.58        93
   macro avg       0.60      0.59      0.57        93
weighted avg       0.61      0.58      0.57        93



In [15]:
accuracy = accuracy_score(y_test, predictions)
print((accuracy*100), "%")

58.06451612903226 %


In [16]:
precision = precision_score(y_test, predictions)
print((predictions*100), "%")

[  0 100   0 100   0 100 100   0   0 100 100 100   0 100 100   0   0 100
 100   0 100 100   0   0   0   0   0   0   0   0 100 100   0   0   0   0
   0   0   0   0   0   0   0 100   0   0   0 100   0   0 100   0   0   0
   0   0 100   0   0 100   0 100   0   0   0   0 100   0   0   0 100 100
   0   0   0   0 100   0 100   0   0 100   0   0   0 100 100   0   0   0
 100   0   0] %


In [17]:
matrix = confusion_matrix(y_test, predictions, labels = [1,0])
print(matrix)

[[20 29]
 [10 34]]


In [18]:
x_influences = pd.DataFrame(gini_model.feature_importances_, index = x_columns)
prnt(x_influences)

NameError: name 'x_columns' is not defined